name: umapgrid
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - adjustText>=1.1.1
    - Flask>=3.0.3
    - matplotlib>=3.8
    - numpy>=1.26.4
    - pandas>=2.2.2
    - python>=3.12
    - scikit-learn>=1.5.0
    - scipy>=1.13.1
    - umap-learn>=0.5
